import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'kn' | 'ta' | 'te';

export const AVAILABLE_LANGUAGES: { code: Language; label: string }[] = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'kn', label: 'ಕನ್ನಡ' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'te', label: 'తెలుగు' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const UI_LANGUAGE_STORAGE_KEY = 'ui_language';

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  en: {
    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.massBalance': 'Mass Balance',
    'nav.knowYourGrains': 'Know Your Grains',
    'nav.analytics': 'Analytics',
    'nav.dataReports': 'Data Reports',
    'nav.grainsViewer': 'Grains Viewer',
    'nav.settings': 'Settings',
    'nav.manuals': 'Manuals',
    'nav.database': 'Database',
    'nav.grainDatabase': 'Grain Database',
    'nav.machineDatabase': 'Machine Database',
    'nav.procurementAnalysis': 'Procurement Analysis',
    'nav.productionAnalysis': 'Production Analysis',
    'nav.milledRiceAnalysis': 'Milled Rice Quality',
    'nav.navigation': 'Navigation',

    // Mass Balance page
    'massBalance.title': 'Mass Balance',
    'massBalance.subtitle': 'Calculate component breakdown from total sample weight',
    'massBalance.machineSelection': 'Machine Selection',
    'massBalance.machineA': 'Machine A',
    'massBalance.machineB': 'Machine B',
    'massBalance.selected': 'Selected',
    'massBalance.machineADesc1': '• High-precision rice analyzer',
    'massBalance.machineADesc2': '• Processing capacity: 100-500g',
    'massBalance.machineADesc3': '• Analysis time: 2-3 minutes',
    'massBalance.machineADesc4': '• Accuracy: ±0.1%',
    'massBalance.machineBDesc1': '• Advanced multi-grain analyzer',
    'massBalance.machineBDesc2': '• Processing capacity: 200-1000g',
    'massBalance.machineBDesc3': '• Analysis time: 1-2 minutes',
    'massBalance.machineBDesc4': '• Accuracy: ±0.05%',
    'massBalance.precisionAnalyzer': 'Precision Analyzer',
    'massBalance.advancedMultiAnalyzer': 'Advanced Multi-Analyzer',
    'massBalance.totalWeightInput': 'Total Sample Weight Input',
    'massBalance.enterTotalWeight': 'Enter Total Weight',
    'massBalance.usingMachine': 'Using Machine',
    'massBalance.forAnalysis': 'for analysis',
    'massBalance.breakdownFormula': 'Breakdown Formula',
    'massBalance.brownRice': 'Brown Rice',
    'massBalance.husk': 'Husk',
    'massBalance.bran': 'Bran',
    'massBalance.paddy': 'Paddy',
    'massBalance.calculatedBreakdown': 'Calculated Breakdown',
    'massBalance.proceedToGrain': 'Proceed to Grain Information',
    
    // Know Your Grains page
    'knowGrains.title': 'Know Your Grains',
    'knowGrains.subtitle': 'Detailed grain properties and parameters',
    'knowGrains.previous': 'Previous',
    'knowGrains.next': 'Next',
    'knowGrains.pageOf': 'Page 1 of 1',
    'knowGrains.grainVisualization': 'Grain Visualization',
    'knowGrains.visualDescription': 'Rice Grain Sample Visualization',
    'knowGrains.visualSubtext': 'Visual representation updates based on entered data',
    'knowGrains.geoProperties': 'Morphological Properties',
    'knowGrains.chemicalProperties': 'Nutritional Properties',
    'knowGrains.gmadProperties': 'GMAD Properties',
    'knowGrains.length': 'Length (mm)',
    'knowGrains.breadth': 'Breadth (mm)',
    'knowGrains.weight': 'Weight (mg)',
    'knowGrains.aspectRatio': 'Aspect Ratio',
    'knowGrains.hardness': 'Hardness (HV)',
    'knowGrains.protein': 'Protein (%)',
    'knowGrains.carbohydrate': 'Carbohydrate (%)',
    'knowGrains.vitamin': 'Vitamin (mg/100g)',
    'knowGrains.mineral': 'Mineral (%)',
    'knowGrains.lipids': 'Lipids (%)',
    'knowGrains.gelatinization': 'Gelatinization Temperature (°C)',
    'knowGrains.moisture': 'Moisture (%)',
    'knowGrains.age': 'Age (Months)',
    'knowGrains.density': 'Density (g/cm³)',
    'knowGrains.addMoreInfo': 'Add More Info',
    'knowGrains.continueToLive': 'Continue to Live Analysis',
    'knowGrains.addProperty': 'Add New Property',
    'knowGrains.propertyName': 'Property Name',
    'knowGrains.propertyValue': 'Property Value',
    'knowGrains.propertyUnit': 'Unit (optional)',
    'knowGrains.cancel': 'Cancel',
    'knowGrains.add': 'Add',
    
    // Settings
    'settings.language': 'Language',
    'settings.hardware': 'Hardware',
    'settings.image': 'Image',
    'settings.reports': 'Reports',

    // Procurement Analysis — Test Preparation
    'procurement.tabPreparation': 'Test Preparation',
    'procurement.tabLive': 'Live Analysis',
    'procurement.tabReports': 'Insights & Reports',
    'procurement.categoryPrefix': 'Category: {category}',
    'procurement.grainInformation': 'Grain Information',
    'procurement.region': 'Region',
    'procurement.nonBasmati': 'Non-Basmati',
    'procurement.basmati': 'Basmati',
    'procurement.appliesSettingsNote': 'Applies the {category} settings configured on the Settings page to this analysis.',
    'procurement.variety': 'Variety',
    'procurement.loadingVarieties': 'Loading varieties...',
    'procurement.noVarietiesInDb': 'No varieties in database',
    'procurement.selectVariety': 'Select variety',
    'procurement.addVarietiesHint': 'Add varieties in Grain Database first; only DB varieties appear here.',
    'procurement.process': 'Process',
    'procurement.selectVarietyFirst': 'Select variety first',
    'procurement.loadingProcesses': 'Loading processes...',
    'procurement.noProcessesForVariety': 'No processes for this variety',
    'procurement.selectProcess': 'Select process',
    'procurement.addProcessesHint': 'No processes in database for this variety. Add in Grain Database.',
    'procurement.harvestSeason': 'Harvest Season',
    'procurement.selectVarietyProcessFirst': 'Select variety and process first',
    'procurement.loadingHarvestSeasons': 'Loading harvest seasons...',
    'procurement.noHarvestSeasons': 'No harvest seasons for this combination',
    'procurement.selectHarvestSeason': 'Select harvest season',
    'procurement.addHarvestSeasonsHint': 'No harvest seasons in database for this variety + process. Add in Grain Database.',
    'procurement.month': 'Month (optional)',
    'procurement.selectHarvestSeasonFirst': 'Select harvest season first',
    'procurement.loadingMonths': 'Loading months...',
    'procurement.noMonths': 'No months for this combination',
    'procurement.selectMonth': 'Select month (optional)',
    'procurement.addMonthsHint': 'No months in database for this combination. Add in Grain Database.',
    'procurement.noOfSamples': 'No. of Samples (1–3)',
    'procurement.samplesPlaceholder': '1–3',
    'procurement.samplingMethod': 'Sampling Method',
    'procurement.selectSamplingMethod': 'Select sampling method',
    'procurement.handMilled': 'Hand milled',
    'procurement.machineMilled': 'Machine milled',
    'procurement.sampleSize': 'Sample Size',
    'procurement.byWeight': 'By Weight',
    'procurement.byCount': 'By Count',
    'procurement.freeWeight': 'Free weight',
    'procurement.freeCount': 'Free count',
    'procurement.maxPlaceholder': 'Max {max}',
    'procurement.gramsUnit': 'g',
    'procurement.grainsUnit': 'grains',
    'procurement.parametersToAnalyse': 'Parameters to Analyse',
    'procurement.chalky': 'Chalky',
    'procurement.discolored': 'Discolored',
    'procurement.chalkyThreshold': 'Chalky Threshold',
    'procurement.purchasedData': 'Purchased Data',
    'procurement.mandi': 'Mandi',
    'procurement.mandiPlaceholder': 'Mandi / Market',
    'procurement.vehicleNumber': 'Vehicle number',
    'procurement.commaSeparatedPlaceholder': 'Comma-separated',
    'procurement.paddyPricePerKg': 'Paddy price per kg (₹)',
    'procurement.kgPerBag': 'kg / bag',
    'procurement.kgPerBagPlaceholder': 'kg per bag',
    'procurement.noOfBags': 'Nos of bags',
    'procurement.transportationCost': 'Transportation cost (₹)',
    'procurement.loadingCost': 'Loading cost (₹)',
    'procurement.moistureSentByTrader': 'Moisture of paddy sent by trader (%)',
    'procurement.yieldEstimation': 'Yield Estimation',
    'procurement.yieldEstimationInputs': 'Yield estimation inputs',
    'procurement.actualInputMoisture': 'Actual input moisture (%)',
    'procurement.impurities': 'Impurities (%)',
    'procurement.immatureGrains': 'Immature grains (%)',
    'procurement.husk': 'Husk (%)',
    'procurement.bran': 'Bran (%)',
    'procurement.headRicePct': 'Head rice (%)',
    'procurement.autoCalculated': 'auto-calculated',
    'procurement.combinedBrokens': 'Combined brokens (%)',
    'procurement.calculatedAfterAnalysis': 'Calculated after analysis',
    'procurement.marginMarketFee': 'Margin / market fee (₹)',
    'procurement.continueToLiveAnalysis': 'Continue to Live Analysis',

    // Live Analysis — dynamic spoken guidance (machine series transitions)
    'liveGuide.machineDoneAnnouncement': '{machine} is done. Please prepare your next sample for {next}, and tap Continue when it is ready.',
    'liveGuide.seriesCompleteAnnouncement': 'All machines in this series are complete. Tap View Insights and Reports to see your results.',
    'liveGuide.sampleRunningAnnouncement': 'Sample {n} running for {machine}.',
  },
  kn: {
    // Sidebar
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.massBalance': 'ದ್ರವ್ಯರಾಶಿ ಸಮತೋಲನ',
    'nav.knowYourGrains': 'ನಿಮ್ಮ ಧಾನ್ಯಗಳನ್ನು ತಿಳಿಯಿರಿ',
    'nav.analytics': 'ವಿಶ್ಲೇಷಣೆಗಳು',
    'nav.dataReports': 'ಡೇಟಾ ವರದಿಗಳು',
    'nav.grainsViewer': 'ಧಾನ್ಯ ವೀಕ್ಷಕ',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'nav.manuals': 'ಕೈಪಿಡಿಗಳು',
    'nav.database': 'ಡೇಟಾಬೇಸ್',
    'nav.grainDatabase': 'ಧಾನ್ಯ ಡೇಟಾಬೇಸ್',
    'nav.machineDatabase': 'ಯಂತ್ರ ಡೇಟಾಬೇಸ್',
    'nav.procurementAnalysis': 'ಖರೀದಿ ವಿಶ್ಲೇಷಣೆ',
    'nav.productionAnalysis': 'ಉತ್ಪಾದನಾ ವಿಶ್ಲೇಷಣೆ',
    'nav.milledRiceAnalysis': 'ಮಿಲ್ಡ್ ಅಕ್ಕಿ ಗುಣಮಟ್ಟ',
    'nav.navigation': 'ನ್ಯಾವಿಗೇಶನ್',

    // Mass Balance page
    'massBalance.title': 'ದ್ರವ್ಯರಾಶಿ ಸಮತೋಲನ',
    'massBalance.subtitle': 'ಒಟ್ಟು ಮಾದರಿ ತೂಕದಿಂದ ಘಟಕ ವಿಭಜನೆಯನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ',
    'massBalance.machineSelection': 'ಯಂತ್ರ ಆಯ್ಕೆ',
    'massBalance.machineA': 'ಯಂತ್ರ A',
    'massBalance.machineB': 'ಯಂತ್ರ B',
    'massBalance.selected': 'ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ',
    'massBalance.machineADesc1': '• ಹೆಚ್ಚಿನ ನಿಖರತೆಯ ಅಕ್ಕಿ ವಿಶ್ಲೇಷಕ',
    'massBalance.machineADesc2': '• ಸಂಸ್ಕರಣಾ ಸಾಮರ್ಥ್ಯ: 100-500ಗ್ರಾ',
    'massBalance.machineADesc3': '• ವಿಶ್ಲೇಷಣೆ ಸಮಯ: 2-3 ನಿಮಿಷಗಳು',
    'massBalance.machineADesc4': '• ನಿಖರತೆ: ±0.1%',
    'massBalance.machineBDesc1': '• ಸುಧಾರಿತ ಬಹು-ಧಾನ್ಯ ವಿಶ್ಲೇಷಕ',
    'massBalance.machineBDesc2': '• ಸಂಸ್ಕರಣಾ ಸಾಮರ್ಥ್ಯ: 200-1000ಗ್ರಾ',
    'massBalance.machineBDesc3': '• ವಿಶ್ಲೇಷಣೆ ಸಮಯ: 1-2 ನಿಮಿಷಗಳು',
    'massBalance.machineBDesc4': '• ನಿಖರತೆ: ±0.05%',
    'massBalance.precisionAnalyzer': 'ನಿಖರತೆ ವಿಶ್ಲೇಷಕ',
    'massBalance.advancedMultiAnalyzer': 'ಸುಧಾರಿತ ಬಹು-ವಿಶ್ಲೇಷಕ',
    'massBalance.totalWeightInput': 'ಒಟ್ಟು ಮಾದರಿ ತೂಕ ಇನ್‌ಪುಟ್',
    'massBalance.enterTotalWeight': 'ಒಟ್ಟು ತೂಕವನ್ನು ನಮೂದಿಸಿ',
    'massBalance.usingMachine': 'ಯಂತ್ರ ಬಳಸುತ್ತಿದೆ',
    'massBalance.forAnalysis': 'ವಿಶ್ಲೇಷಣೆಗಾಗಿ',
    'massBalance.breakdownFormula': 'ವಿಭಜನೆ ಸೂತ್ರ',
    'massBalance.brownRice': 'ಕಂದು ಅಕ್ಕಿ',
    'massBalance.husk': 'ಹೊಟ್ಟು',
    'massBalance.bran': 'ಹೊಟ್ಟೆ',
    'massBalance.paddy': 'ಧಾನ್ಯ',
    'massBalance.calculatedBreakdown': 'ಲೆಕ್ಕಾಚಾರದ ವಿಭಜನೆ',
    'massBalance.proceedToGrain': 'ಧಾನ್ಯ ಮಾಹಿತಿಗೆ ಮುಂದುವರಿಯಿರಿ',
    
    // Know Your Grains page
    'knowGrains.title': 'ನಿಮ್ಮ ಧಾನ್ಯಗಳನ್ನು ತಿಳಿಯಿರಿ',
    'knowGrains.subtitle': 'ವಿವರವಾದ ಧಾನ್ಯ ಗುಣಲಕ್ಷಣಗಳು ಮತ್ತು ನಿಯತಾಂಕಗಳು',
    'knowGrains.previous': 'ಹಿಂದಿನ',
    'knowGrains.next': 'ಮುಂದಿನ',
    'knowGrains.pageOf': 'ಪುಟ 1 ರ 1',
    'knowGrains.grainVisualization': 'ಧಾನ್ಯ ದೃಶ್ಯೀಕರಣ',
    'knowGrains.visualDescription': 'ಅಕ್ಕಿ ಧಾನ್ಯ ಮಾದರಿ ದೃಶ್ಯೀಕರಣ',
    'knowGrains.visualSubtext': 'ನಮೂದಿಸಿದ ಡೇಟಾದ ಆಧಾರದ ಮೇಲೆ ದೃಶ್ಯ ಪ್ರಾತಿನಿಧ್ಯ ನವೀಕರಣಗೊಳ್ಳುತ್ತದೆ',
    'knowGrains.geoProperties': 'ಭೌಗೋಳಿಕ ಗುಣಲಕ್ಷಣಗಳು',
    'knowGrains.chemicalProperties': 'ರಾಸಾಯನಿಕ ಗುಣಲಕ್ಷಣಗಳು',
    'knowGrains.gmadProperties': 'ಜಿಮ್ಯಾಡ್ ಗುಣಲಕ್ಷಣಗಳು',
    'knowGrains.length': 'ಉದ್ದ (ಮಿಮೀ)',
    'knowGrains.breadth': 'ಅಗಲ (ಮಿಮೀ)',
    'knowGrains.weight': 'ತೂಕ (ಮಿಗ್ರಾ)',
    'knowGrains.aspectRatio': 'ಆಕಾರ ಅನುಪಾತ',
    'knowGrains.hardness': 'ಗಡಸುತನ (HV)',
    'knowGrains.protein': 'ಪ್ರೋಟೀನ್ (%)',
    'knowGrains.carbohydrate': 'ಕಾರ್ಬೋಹೈಡ್ರೇಟ್ (%)',
    'knowGrains.vitamin': 'ವಿಟಮಿನ್ (ಮಿಗ್ರಾ/100ಗ್ರಾ)',
    'knowGrains.mineral': 'ಖನಿಜ (%)',
    'knowGrains.lipids': 'ಲಿಪಿಡ್‌ಗಳು (%)',
    'knowGrains.gelatinization': 'ಜೆಲಟಿನೀಕರಣ ತಾಪಮಾನ (°C)',
    'knowGrains.moisture': 'ತೇವಾಂಶ (%)',
    'knowGrains.age': 'ವಯಸ್ಸು (ತಿಂಗಳುಗಳು)',
    'knowGrains.density': 'ಸಾಂದ್ರತೆ (ಗ್ರಾ/ಸೆಮೀ³)',
    'knowGrains.addMoreInfo': 'ಹೆಚ್ಚಿನ ಮಾಹಿತಿ ಸೇರಿಸಿ',
    'knowGrains.continueToLive': 'ನೇರ ವಿಶ್ಲೇಷಣೆಗೆ ಮುಂದುವರಿಯಿರಿ',
    'knowGrains.addProperty': 'ಹೊಸ ಗುಣಲಕ್ಷಣ ಸೇರಿಸಿ',
    'knowGrains.propertyName': 'ಗುಣಲಕ್ಷಣದ ಹೆಸರು',
    'knowGrains.propertyValue': 'ಗುಣಲಕ್ಷಣದ ಮೌಲ್ಯ',
    'knowGrains.propertyUnit': 'ಘಟಕ (ಐಚ್ಛಿಕ)',
    'knowGrains.cancel': 'ರದ್ದುಮಾಡಿ',
    'knowGrains.add': 'ಸೇರಿಸಿ',
    
    // Settings
    'settings.language': 'ಭಾಷೆ',
    'settings.hardware': 'ಹಾರ್ಡ್‌ವೇರ್',
    'settings.image': 'ಚಿತ್ರ',
    'settings.reports': 'ವರದಿಗಳು',

    // Procurement Analysis — Test Preparation
    'procurement.tabPreparation': 'ಟೆಸ್ಟ್ ಸಿದ್ಧತೆ',
    'procurement.tabLive': 'ಲೈವ್ ಅನಾಲಿಸಿಸ್',
    'procurement.tabReports': 'ಇನ್‌ಸೈಟ್ಸ್ ಮತ್ತು ರಿಪೋರ್ಟ್‌ಗಳು',
    'procurement.categoryPrefix': 'ವರ್ಗ: {category}',
    'procurement.grainInformation': 'ಗ್ರೇನ್ ಮಾಹಿತಿ',
    'procurement.region': 'ರೀಜನ್',
    'procurement.nonBasmati': 'ನಾನ್-ಬಾಸ್ಮತಿ',
    'procurement.basmati': 'ಬಾಸ್ಮತಿ',
    'procurement.appliesSettingsNote': 'ಇದು Settings ಪೇಜ್‌ನಲ್ಲಿ ಸಂರಚಿಸಲಾದ {category} ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಈ ವಿಶ್ಲೇಷಣೆಗೆ ಅನ್ವಯಿಸುತ್ತದೆ.',
    'procurement.variety': 'ವೆರೈಟಿ',
    'procurement.loadingVarieties': 'ವೆರೈಟಿಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...',
    'procurement.noVarietiesInDb': 'ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ವೆರೈಟಿಗಳಿಲ್ಲ',
    'procurement.selectVariety': 'ವೆರೈಟಿ ಆಯ್ಕೆಮಾಡಿ',
    'procurement.addVarietiesHint': 'ಮೊದಲು Grain Database ನಲ್ಲಿ ವೆರೈಟಿಗಳನ್ನು ಸೇರಿಸಿ; ಇಲ್ಲಿ ಡೇಟಾಬೇಸ್‌ನ ವೆರೈಟಿಗಳು ಮಾತ್ರ ಕಾಣಿಸುತ್ತವೆ.',
    'procurement.process': 'ಪ್ರೊಸೆಸ್',
    'procurement.selectVarietyFirst': 'ಮೊದಲು ವೆರೈಟಿ ಆಯ್ಕೆಮಾಡಿ',
    'procurement.loadingProcesses': 'ಪ್ರೊಸೆಸ್‌ಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...',
    'procurement.noProcessesForVariety': 'ಈ ವೆರೈಟಿಗೆ ಯಾವುದೇ ಪ್ರೊಸೆಸ್ ಇಲ್ಲ',
    'procurement.selectProcess': 'ಪ್ರೊಸೆಸ್ ಆಯ್ಕೆಮಾಡಿ',
    'procurement.addProcessesHint': 'ಈ ವೆರೈಟಿಗೆ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಯಾವುದೇ ಪ್ರೊಸೆಸ್ ಇಲ್ಲ. Grain Database ನಲ್ಲಿ ಸೇರಿಸಿ.',
    'procurement.harvestSeason': 'ಹಾರ್ವೆಸ್ಟ್ ಸೀಸನ್',
    'procurement.selectVarietyProcessFirst': 'ಮೊದಲು ವೆರೈಟಿ ಮತ್ತು ಪ್ರೊಸೆಸ್ ಆಯ್ಕೆಮಾಡಿ',
    'procurement.loadingHarvestSeasons': 'ಹಾರ್ವೆಸ್ಟ್ ಸೀಸನ್‌ಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...',
    'procurement.noHarvestSeasons': 'ಈ ಸಂಯೋಜನೆಗೆ ಯಾವುದೇ ಹಾರ್ವೆಸ್ಟ್ ಸೀಸನ್ ಇಲ್ಲ',
    'procurement.selectHarvestSeason': 'ಹಾರ್ವೆಸ್ಟ್ ಸೀಸನ್ ಆಯ್ಕೆಮಾಡಿ',
    'procurement.addHarvestSeasonsHint': 'ಈ ವೆರೈಟಿ + ಪ್ರೊಸೆಸ್‌ಗೆ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಯಾವುದೇ ಹಾರ್ವೆಸ್ಟ್ ಸೀಸನ್ ಇಲ್ಲ. Grain Database ನಲ್ಲಿ ಸೇರಿಸಿ.',
    'procurement.month': 'ತಿಂಗಳು (ಐಚ್ಛಿಕ)',
    'procurement.selectHarvestSeasonFirst': 'ಮೊದಲು ಹಾರ್ವೆಸ್ಟ್ ಸೀಸನ್ ಆಯ್ಕೆಮಾಡಿ',
    'procurement.loadingMonths': 'ತಿಂಗಳುಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...',
    'procurement.noMonths': 'ಈ ಸಂಯೋಜನೆಗೆ ಯಾವುದೇ ತಿಂಗಳು ಇಲ್ಲ',
    'procurement.selectMonth': 'ತಿಂಗಳು ಆಯ್ಕೆಮಾಡಿ (ಐಚ್ಛಿಕ)',
    'procurement.addMonthsHint': 'ಈ ಸಂಯೋಜನೆಗೆ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಯಾವುದೇ ತಿಂಗಳು ಇಲ್ಲ. Grain Database ನಲ್ಲಿ ಸೇರಿಸಿ.',
    'procurement.noOfSamples': 'ಸ್ಯಾಂಪಲ್‌ಗಳ ಸಂಖ್ಯೆ (1–3)',
    'procurement.samplesPlaceholder': '1–3',
    'procurement.samplingMethod': 'ಸ್ಯಾಂಪಲಿಂಗ್ ವಿಧಾನ',
    'procurement.selectSamplingMethod': 'ಸ್ಯಾಂಪಲಿಂಗ್ ವಿಧಾನ ಆಯ್ಕೆಮಾಡಿ',
    'procurement.handMilled': 'ಹ್ಯಾಂಡ್ ಮಿಲ್ಡ್',
    'procurement.machineMilled': 'ಮಷಿನ್ ಮಿಲ್ಡ್',
    'procurement.sampleSize': 'ಸ್ಯಾಂಪಲ್ ಗಾತ್ರ',
    'procurement.byWeight': 'ತೂಕದ ಪ್ರಕಾರ',
    'procurement.byCount': 'ಎಣಿಕೆಯ ಪ್ರಕಾರ',
    'procurement.freeWeight': 'ಫ್ರೀ ತೂಕ',
    'procurement.freeCount': 'ಫ್ರೀ ಎಣಿಕೆ',
    'procurement.maxPlaceholder': 'ಗರಿಷ್ಠ {max}',
    'procurement.gramsUnit': 'ಗ್ರಾಂ',
    'procurement.grainsUnit': 'ಕಾಳುಗಳು',
    'procurement.parametersToAnalyse': 'ವಿಶ್ಲೇಷಿಸಬೇಕಾದ ಪ್ಯಾರಾಮೀಟರ್‌ಗಳು',
    'procurement.chalky': 'Chalky',
    'procurement.discolored': 'Discolored',
    'procurement.chalkyThreshold': 'Chalky ಥ್ರೆಶೋಲ್ಡ್',
    'procurement.purchasedData': 'ಖರೀದಿ ಡೇಟಾ',
    'procurement.mandi': 'ಮಂಡಿ',
    'procurement.mandiPlaceholder': 'ಮಂಡಿ / ಮಾರುಕಟ್ಟೆ',
    'procurement.vehicleNumber': 'ವಾಹನ ಸಂಖ್ಯೆ',
    'procurement.commaSeparatedPlaceholder': 'ಅಲ್ಪವಿರಾಮದಿಂದ ಬೇರ್ಪಡಿಸಿ',
    'procurement.paddyPricePerKg': 'ಭತ್ತದ ಬೆಲೆ ಪ್ರತಿ ಕೆಜಿ (₹)',
    'procurement.kgPerBag': 'ಕೆಜಿ / ಚೀಲ',
    'procurement.kgPerBagPlaceholder': 'ಪ್ರತಿ ಚೀಲಕ್ಕೆ ಕೆಜಿ',
    'procurement.noOfBags': 'ಚೀಲಗಳ ಸಂಖ್ಯೆ',
    'procurement.transportationCost': 'ಸಾಗಣೆ ವೆಚ್ಚ (₹)',
    'procurement.loadingCost': 'ಲೋಡಿಂಗ್ ವೆಚ್ಚ (₹)',
    'procurement.moistureSentByTrader': 'ವ್ಯಾಪಾರಿ ಕಳುಹಿಸಿದ ಭತ್ತದ ತೇವಾಂಶ (%)',
    'procurement.yieldEstimation': 'ಇಳುವರಿ ಅಂದಾಜು',
    'procurement.yieldEstimationInputs': 'ಇಳುವರಿ ಅಂದಾಜು ಇನ್‌ಪುಟ್‌ಗಳು',
    'procurement.actualInputMoisture': 'ವಾಸ್ತವ ಇನ್‌ಪುಟ್ ತೇವಾಂಶ (%)',
    'procurement.impurities': 'ಕಲ್ಮಶಗಳು (%)',
    'procurement.immatureGrains': 'ಅಪಕ್ವ ಕಾಳುಗಳು (%)',
    'procurement.husk': 'ಹೊಟ್ಟು (%)',
    'procurement.bran': 'ಹೊಟ್ಟೆ (%)',
    'procurement.headRicePct': 'Head Rice (%)',
    'procurement.autoCalculated': 'ಸ್ವಯಂ-ಲೆಕ್ಕಾಚಾರ',
    'procurement.combinedBrokens': 'ಒಟ್ಟು ಟೂಟಿದ ಅಕ್ಕಿ (%)',
    'procurement.calculatedAfterAnalysis': 'ವಿಶ್ಲೇಷಣೆಯ ನಂತರ ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತದೆ',
    'procurement.marginMarketFee': 'ಮಾರ್ಜಿನ್ / ಮಾರುಕಟ್ಟೆ ಶುಲ್ಕ (₹)',
    'procurement.continueToLiveAnalysis': 'Live Analysis ಗೆ ಮುಂದುವರಿಯಿರಿ',

    // Live Analysis — dynamic spoken guidance (machine series transitions)
    'liveGuide.machineDoneAnnouncement': '{machine} ಮುಗಿದಿದೆ. ದಯವಿಟ್ಟು {next} ಗಾಗಿ ಮುಂದಿನ ಸ್ಯಾಂಪಲ್ ಸಿದ್ಧಪಡಿಸಿ, ಸಿದ್ಧವಾದಾಗ Continue ಒತ್ತಿ.',
    'liveGuide.seriesCompleteAnnouncement': 'ಈ ಸೀರೀಸ್‌ನ ಎಲ್ಲಾ ಮಷಿನ್‌ಗಳು ಪೂರ್ಣಗೊಂಡಿವೆ. ನಿಮ್ಮ ಫಲಿತಾಂಶಗಳನ್ನು ನೋಡಲು View Insights and Reports ಒತ್ತಿ.',
    'liveGuide.sampleRunningAnnouncement': '{machine} ಗಾಗಿ ಸ್ಯಾಂಪಲ್ {n} ಚಾಲನೆಯಲ್ಲಿದೆ.',
  },
  hi: {
    // Sidebar
    'nav.dashboard': 'डैशबोर्ड',
    'nav.massBalance': 'मास बैलेंस',
    'nav.knowYourGrains': 'अपने अनाज को जानें',
    'nav.analytics': 'एनालिटिक्स',
    'nav.dataReports': 'डेटा रिपोर्ट',
    'nav.grainsViewer': 'ग्रेन व्यूअर',
    'nav.settings': 'सेटिंग्स',
    'nav.manuals': 'मैनुअल',
    'nav.database': 'डेटाबेस',
    'nav.grainDatabase': 'ग्रेन डेटाबेस',
    'nav.machineDatabase': 'मशीन डेटाबेस',
    'nav.procurementAnalysis': 'खरीद विश्लेषण',
    'nav.productionAnalysis': 'उत्पादन विश्लेषण',
    'nav.milledRiceAnalysis': 'मिल्ड राइस क्वालिटी',
    'nav.navigation': 'नेविगेशन',

    // Mass Balance page
    'massBalance.title': 'मास बैलेंस',
    'massBalance.subtitle': 'कुल सैंपल वज़न से घटकों का विभाजन निकालें',
    'massBalance.machineSelection': 'मशीन चयन',
    'massBalance.machineA': 'मशीन A',
    'massBalance.machineB': 'मशीन B',
    'massBalance.selected': 'चयनित',
    'massBalance.machineADesc1': '• उच्च-सटीकता राइस एनालाइज़र',
    'massBalance.machineADesc2': '• प्रोसेसिंग क्षमता: 100-500 ग्राम',
    'massBalance.machineADesc3': '• विश्लेषण समय: 2-3 मिनट',
    'massBalance.machineADesc4': '• सटीकता: ±0.1%',
    'massBalance.machineBDesc1': '• एडवांस्ड मल्टी-ग्रेन एनालाइज़र',
    'massBalance.machineBDesc2': '• प्रोसेसिंग क्षमता: 200-1000 ग्राम',
    'massBalance.machineBDesc3': '• विश्लेषण समय: 1-2 मिनट',
    'massBalance.machineBDesc4': '• सटीकता: ±0.05%',
    'massBalance.precisionAnalyzer': 'प्रिसिज़न एनालाइज़र',
    'massBalance.advancedMultiAnalyzer': 'एडवांस्ड मल्टी-एनालाइज़र',
    'massBalance.totalWeightInput': 'कुल सैंपल वज़न इनपुट',
    'massBalance.enterTotalWeight': 'कुल वज़न दर्ज करें',
    'massBalance.usingMachine': 'उपयोग की जा रही मशीन',
    'massBalance.forAnalysis': 'विश्लेषण के लिए',
    'massBalance.breakdownFormula': 'विभाजन सूत्र',
    'massBalance.brownRice': 'ब्राउन राइस',
    'massBalance.husk': 'भूसी',
    'massBalance.bran': 'चोकर',
    'massBalance.paddy': 'धान',
    'massBalance.calculatedBreakdown': 'गणना किया गया विभाजन',
    'massBalance.proceedToGrain': 'ग्रेन जानकारी पर आगे बढ़ें',

    // Know Your Grains page
    'knowGrains.title': 'अपने अनाज को जानें',
    'knowGrains.subtitle': 'विस्तृत ग्रेन गुण और पैरामीटर',
    'knowGrains.previous': 'पिछला',
    'knowGrains.next': 'अगला',
    'knowGrains.pageOf': 'पेज 1 का 1',
    'knowGrains.grainVisualization': 'ग्रेन विज़ुअलाइज़ेशन',
    'knowGrains.visualDescription': 'राइस ग्रेन सैंपल विज़ुअलाइज़ेशन',
    'knowGrains.visualSubtext': 'दर्ज किए गए डेटा के आधार पर विज़ुअल प्रतिनिधित्व अपडेट होता है',
    'knowGrains.geoProperties': 'आकारिकीय गुण',
    'knowGrains.chemicalProperties': 'पोषण गुण',
    'knowGrains.gmadProperties': 'GMAD गुण',
    'knowGrains.length': 'लंबाई (मिमी)',
    'knowGrains.breadth': 'चौड़ाई (मिमी)',
    'knowGrains.weight': 'वज़न (मिग्रा)',
    'knowGrains.aspectRatio': 'आस्पेक्ट रेशियो',
    'knowGrains.hardness': 'कठोरता (HV)',
    'knowGrains.protein': 'प्रोटीन (%)',
    'knowGrains.carbohydrate': 'कार्बोहाइड्रेट (%)',
    'knowGrains.vitamin': 'विटामिन (मिग्रा/100 ग्राम)',
    'knowGrains.mineral': 'खनिज (%)',
    'knowGrains.lipids': 'लिपिड्स (%)',
    'knowGrains.gelatinization': 'जिलेटिनाइज़ेशन तापमान (°C)',
    'knowGrains.moisture': 'नमी (%)',
    'knowGrains.age': 'आयु (महीने)',
    'knowGrains.density': 'घनत्व (ग्रा/सेमी³)',
    'knowGrains.addMoreInfo': 'अधिक जानकारी जोड़ें',
    'knowGrains.continueToLive': 'लाइव एनालिसिस पर जारी रखें',
    'knowGrains.addProperty': 'नया गुण जोड़ें',
    'knowGrains.propertyName': 'गुण का नाम',
    'knowGrains.propertyValue': 'गुण का मान',
    'knowGrains.propertyUnit': 'इकाई (वैकल्पिक)',
    'knowGrains.cancel': 'रद्द करें',
    'knowGrains.add': 'जोड़ें',

    // Settings
    'settings.language': 'भाषा',
    'settings.hardware': 'हार्डवेयर',
    'settings.image': 'इमेज',
    'settings.reports': 'रिपोर्ट',

    // Procurement Analysis — Test Preparation
    'procurement.tabPreparation': 'टेस्ट तैयारी',
    'procurement.tabLive': 'लाइव एनालिसिस',
    'procurement.tabReports': 'इनसाइट्स और रिपोर्ट',
    'procurement.categoryPrefix': 'श्रेणी: {category}',
    'procurement.grainInformation': 'ग्रेन जानकारी',
    'procurement.region': 'रीजन',
    'procurement.nonBasmati': 'नॉन-बासमती',
    'procurement.basmati': 'बासमती',
    'procurement.appliesSettingsNote': 'यह इस विश्लेषण पर Settings पेज में सेट की गई {category} सेटिंग्स लागू करता है।',
    'procurement.variety': 'वैरायटी',
    'procurement.loadingVarieties': 'वैरायटी लोड हो रही हैं...',
    'procurement.noVarietiesInDb': 'डेटाबेस में कोई वैरायटी नहीं',
    'procurement.selectVariety': 'वैरायटी चुनें',
    'procurement.addVarietiesHint': 'पहले Grain Database में वैरायटी जोड़ें; यहाँ केवल डेटाबेस की वैरायटी दिखेंगी।',
    'procurement.process': 'प्रोसेस',
    'procurement.selectVarietyFirst': 'पहले वैरायटी चुनें',
    'procurement.loadingProcesses': 'प्रोसेस लोड हो रहे हैं...',
    'procurement.noProcessesForVariety': 'इस वैरायटी के लिए कोई प्रोसेस नहीं',
    'procurement.selectProcess': 'प्रोसेस चुनें',
    'procurement.addProcessesHint': 'इस वैरायटी के लिए डेटाबेस में कोई प्रोसेस नहीं है। Grain Database में जोड़ें।',
    'procurement.harvestSeason': 'हार्वेस्ट सीज़न',
    'procurement.selectVarietyProcessFirst': 'पहले वैरायटी और प्रोसेस चुनें',
    'procurement.loadingHarvestSeasons': 'हार्वेस्ट सीज़न लोड हो रहे हैं...',
    'procurement.noHarvestSeasons': 'इस संयोजन के लिए कोई हार्वेस्ट सीज़न नहीं',
    'procurement.selectHarvestSeason': 'हार्वेस्ट सीज़न चुनें',
    'procurement.addHarvestSeasonsHint': 'इस वैरायटी + प्रोसेस के लिए डेटाबेस में कोई हार्वेस्ट सीज़न नहीं है। Grain Database में जोड़ें।',
    'procurement.month': 'महीना (वैकल्पिक)',
    'procurement.selectHarvestSeasonFirst': 'पहले हार्वेस्ट सीज़न चुनें',
    'procurement.loadingMonths': 'महीने लोड हो रहे हैं...',
    'procurement.noMonths': 'इस संयोजन के लिए कोई महीना नहीं',
    'procurement.selectMonth': 'महीना चुनें (वैकल्पिक)',
    'procurement.addMonthsHint': 'इस संयोजन के लिए डेटाबेस में कोई महीना नहीं है। Grain Database में जोड़ें।',
    'procurement.noOfSamples': 'सैंपलों की संख्या (1–3)',
    'procurement.samplesPlaceholder': '1–3',
    'procurement.samplingMethod': 'सैंपलिंग मेथड',
    'procurement.selectSamplingMethod': 'सैंपलिंग मेथड चुनें',
    'procurement.handMilled': 'हैंड मिल्ड',
    'procurement.machineMilled': 'मशीन मिल्ड',
    'procurement.sampleSize': 'सैंपल साइज़',
    'procurement.byWeight': 'वज़न के अनुसार',
    'procurement.byCount': 'गिनती के अनुसार',
    'procurement.freeWeight': 'फ्री वज़न',
    'procurement.freeCount': 'फ्री गिनती',
    'procurement.maxPlaceholder': 'अधिकतम {max}',
    'procurement.gramsUnit': 'ग्राम',
    'procurement.grainsUnit': 'दाने',
    'procurement.parametersToAnalyse': 'विश्लेषण करने के पैरामीटर',
    'procurement.chalky': 'Chalky',
    'procurement.discolored': 'Discolored',
    'procurement.chalkyThreshold': 'Chalky थ्रेशोल्ड',
    'procurement.purchasedData': 'खरीद डेटा',
    'procurement.mandi': 'मंडी',
    'procurement.mandiPlaceholder': 'मंडी / बाज़ार',
    'procurement.vehicleNumber': 'गाड़ी नंबर',
    'procurement.commaSeparatedPlaceholder': 'कॉमा से अलग करें',
    'procurement.paddyPricePerKg': 'धान की कीमत प्रति किलो (₹)',
    'procurement.kgPerBag': 'किलो / बोरी',
    'procurement.kgPerBagPlaceholder': 'किलो प्रति बोरी',
    'procurement.noOfBags': 'बोरियों की संख्या',
    'procurement.transportationCost': 'परिवहन लागत (₹)',
    'procurement.loadingCost': 'लोडिंग लागत (₹)',
    'procurement.moistureSentByTrader': 'व्यापारी द्वारा भेजी गई धान की नमी (%)',
    'procurement.yieldEstimation': 'यील्ड अनुमान',
    'procurement.yieldEstimationInputs': 'यील्ड अनुमान इनपुट',
    'procurement.actualInputMoisture': 'वास्तविक इनपुट नमी (%)',
    'procurement.impurities': 'अशुद्धियाँ (%)',
    'procurement.immatureGrains': 'अपरिपक्व दाने (%)',
    'procurement.husk': 'भूसी (%)',
    'procurement.bran': 'चोकर (%)',
    'procurement.headRicePct': 'हेड राइस (%)',
    'procurement.autoCalculated': 'स्वतः गणना',
    'procurement.combinedBrokens': 'कुल टूटा चावल (%)',
    'procurement.calculatedAfterAnalysis': 'विश्लेषण के बाद गणना होगी',
    'procurement.marginMarketFee': 'मार्जिन / मार्केट फ़ीस (₹)',
    'procurement.continueToLiveAnalysis': 'Live Analysis पर जारी रखें',

    // Live Analysis — dynamic spoken guidance (machine series transitions)
    'liveGuide.machineDoneAnnouncement': '{machine} पूरा हो गया है। कृपया {next} के लिए अगला सैंपल तैयार करें, और तैयार होने पर Continue दबाएँ।',
    'liveGuide.seriesCompleteAnnouncement': 'इस सीरीज़ की सभी मशीनें पूरी हो गई हैं। अपने नतीजे देखने के लिए View Insights and Reports दबाएँ।',
    'liveGuide.sampleRunningAnnouncement': '{machine} के लिए सैंपल {n} चल रहा है।',
  },
  ta: {
    // Sidebar
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.massBalance': 'மாஸ் பேலன்ஸ்',
    'nav.knowYourGrains': 'உங்கள் தானியங்களை அறிக',
    'nav.analytics': 'பகுப்பாய்வு',
    'nav.dataReports': 'தரவு அறிக்கைகள்',
    'nav.grainsViewer': 'தானிய வியூவர்',
    'nav.settings': 'அமைப்புகள்',
    'nav.manuals': 'கையேடுகள்',
    'nav.database': 'தரவுத்தளம்',
    'nav.grainDatabase': 'தானிய தரவுத்தளம்',
    'nav.machineDatabase': 'மெஷின் தரவுத்தளம்',
    'nav.procurementAnalysis': 'கொள்முதல் பகுப்பாய்வு',
    'nav.productionAnalysis': 'உற்பத்தி பகுப்பாய்வு',
    'nav.milledRiceAnalysis': 'மில் செய்த அரிசி தரம்',
    'nav.navigation': 'வழிசெலுத்தல்',

    // Mass Balance page
    'massBalance.title': 'மாஸ் பேலன்ஸ்',
    'massBalance.subtitle': 'மொத்த மாதிரி எடையிலிருந்து கூறுகளின் பிரிவைக் கணக்கிடுங்கள்',
    'massBalance.machineSelection': 'மெஷின் தேர்வு',
    'massBalance.machineA': 'மெஷின் A',
    'massBalance.machineB': 'மெஷின் B',
    'massBalance.selected': 'தேர்ந்தெடுக்கப்பட்டது',
    'massBalance.machineADesc1': '• உயர்-துல்லிய அரிசி பகுப்பாய்வி',
    'massBalance.machineADesc2': '• செயலாக்க திறன்: 100-500 கிராம்',
    'massBalance.machineADesc3': '• பகுப்பாய்வு நேரம்: 2-3 நிமிடங்கள்',
    'massBalance.machineADesc4': '• துல்லியம்: ±0.1%',
    'massBalance.machineBDesc1': '• மேம்பட்ட பல்-தானிய பகுப்பாய்வி',
    'massBalance.machineBDesc2': '• செயலாக்க திறன்: 200-1000 கிராம்',
    'massBalance.machineBDesc3': '• பகுப்பாய்வு நேரம்: 1-2 நிமிடங்கள்',
    'massBalance.machineBDesc4': '• துல்லியம்: ±0.05%',
    'massBalance.precisionAnalyzer': 'பிரிசிஷன் அனலைசர்',
    'massBalance.advancedMultiAnalyzer': 'மேம்பட்ட மல்டி-அனலைசர்',
    'massBalance.totalWeightInput': 'மொத்த மாதிரி எடை உள்ளீடு',
    'massBalance.enterTotalWeight': 'மொத்த எடையை உள்ளிடவும்',
    'massBalance.usingMachine': 'பயன்படுத்தும் மெஷின்',
    'massBalance.forAnalysis': 'பகுப்பாய்விற்கு',
    'massBalance.breakdownFormula': 'பிரிவு சூத்திரம்',
    'massBalance.brownRice': 'பிரவுன் ரைஸ்',
    'massBalance.husk': 'உமி',
    'massBalance.bran': 'தவிடு',
    'massBalance.paddy': 'நெல்',
    'massBalance.calculatedBreakdown': 'கணக்கிடப்பட்ட பிரிவு',
    'massBalance.proceedToGrain': 'தானிய தகவலுக்குத் தொடரவும்',

    // Know Your Grains page
    'knowGrains.title': 'உங்கள் தானியங்களை அறிக',
    'knowGrains.subtitle': 'விரிவான தானிய பண்புகள் மற்றும் அளவுருக்கள்',
    'knowGrains.previous': 'முந்தைய',
    'knowGrains.next': 'அடுத்து',
    'knowGrains.pageOf': 'பக்கம் 1 / 1',
    'knowGrains.grainVisualization': 'தானிய காட்சிப்படுத்தல்',
    'knowGrains.visualDescription': 'அரிசி தானிய மாதிரி காட்சிப்படுத்தல்',
    'knowGrains.visualSubtext': 'உள்ளிடப்பட்ட தரவின் அடிப்படையில் காட்சிப்படுத்தல் புதுப்பிக்கப்படும்',
    'knowGrains.geoProperties': 'உருவவியல் பண்புகள்',
    'knowGrains.chemicalProperties': 'ஊட்டச்சத்து பண்புகள்',
    'knowGrains.gmadProperties': 'GMAD பண்புகள்',
    'knowGrains.length': 'நீளம் (மிமீ)',
    'knowGrains.breadth': 'அகலம் (மிமீ)',
    'knowGrains.weight': 'எடை (மி.கி.)',
    'knowGrains.aspectRatio': 'அஸ்பெக்ட் ரேஷியோ',
    'knowGrains.hardness': 'கடினத்தன்மை (HV)',
    'knowGrains.protein': 'புரதம் (%)',
    'knowGrains.carbohydrate': 'கார்போஹைட்ரேட் (%)',
    'knowGrains.vitamin': 'வைட்டமின் (மி.கி./100கி.)',
    'knowGrains.mineral': 'தாது (%)',
    'knowGrains.lipids': 'கொழுப்புகள் (%)',
    'knowGrains.gelatinization': 'ஜெலட்டினைசேஷன் வெப்பநிலை (°C)',
    'knowGrains.moisture': 'ஈரப்பதம் (%)',
    'knowGrains.age': 'வயது (மாதங்கள்)',
    'knowGrains.density': 'அடர்த்தி (கி./செமீ³)',
    'knowGrains.addMoreInfo': 'மேலும் தகவல் சேர்க்க',
    'knowGrains.continueToLive': 'லைவ் அனாலிசிஸுக்குத் தொடரவும்',
    'knowGrains.addProperty': 'புதிய பண்பு சேர்க்க',
    'knowGrains.propertyName': 'பண்பின் பெயர்',
    'knowGrains.propertyValue': 'பண்பின் மதிப்பு',
    'knowGrains.propertyUnit': 'அலகு (விருப்பம்)',
    'knowGrains.cancel': 'ரத்து செய்',
    'knowGrains.add': 'சேர்',

    // Settings
    'settings.language': 'மொழி',
    'settings.hardware': 'ஹார்ட்வேர்',
    'settings.image': 'படம்',
    'settings.reports': 'அறிக்கைகள்',

    // Procurement Analysis — Test Preparation
    'procurement.tabPreparation': 'சோதனை தயாரிப்பு',
    'procurement.tabLive': 'லைவ் அனாலிசிஸ்',
    'procurement.tabReports': 'இன்சைட்ஸ் & அறிக்கைகள்',
    'procurement.categoryPrefix': 'வகை: {category}',
    'procurement.grainInformation': 'தானிய தகவல்',
    'procurement.region': 'ரீஜியன்',
    'procurement.nonBasmati': 'நான்-பாஸ்மதி',
    'procurement.basmati': 'பாஸ்மதி',
    'procurement.appliesSettingsNote': 'இது Settings பக்கத்தில் அமைக்கப்பட்ட {category} அமைப்புகளை இந்த பகுப்பாய்வுக்குப் பயன்படுத்துகிறது.',
    'procurement.variety': 'வெரைட்டி',
    'procurement.loadingVarieties': 'வெரைட்டிகள் ஏற்றப்படுகின்றன...',
    'procurement.noVarietiesInDb': 'தரவுத்தளத்தில் வெரைட்டிகள் இல்லை',
    'procurement.selectVariety': 'வெரைட்டியைத் தேர்ந்தெடுக்கவும்',
    'procurement.addVarietiesHint': 'முதலில் Grain Database இல் வெரைட்டிகளைச் சேர்க்கவும்; இங்கே தரவுத்தள வெரைட்டிகள் மட்டுமே தோன்றும்.',
    'procurement.process': 'ப்ராசஸ்',
    'procurement.selectVarietyFirst': 'முதலில் வெரைட்டியைத் தேர்ந்தெடுக்கவும்',
    'procurement.loadingProcesses': 'ப்ராசஸ்கள் ஏற்றப்படுகின்றன...',
    'procurement.noProcessesForVariety': 'இந்த வெரைட்டிக்கு ப்ராசஸ் இல்லை',
    'procurement.selectProcess': 'ப்ராசஸைத் தேர்ந்தெடுக்கவும்',
    'procurement.addProcessesHint': 'இந்த வெரைட்டிக்கு தரவுத்தளத்தில் ப்ராசஸ் இல்லை. Grain Database இல் சேர்க்கவும்.',
    'procurement.harvestSeason': 'அறுவடை பருவம்',
    'procurement.selectVarietyProcessFirst': 'முதலில் வெரைட்டி மற்றும் ப்ராசஸைத் தேர்ந்தெடுக்கவும்',
    'procurement.loadingHarvestSeasons': 'அறுவடை பருவங்கள் ஏற்றப்படுகின்றன...',
    'procurement.noHarvestSeasons': 'இந்த சேர்க்கைக்கு அறுவடை பருவம் இல்லை',
    'procurement.selectHarvestSeason': 'அறுவடை பருவத்தைத் தேர்ந்தெடுக்கவும்',
    'procurement.addHarvestSeasonsHint': 'இந்த வெரைட்டி + ப்ராசஸுக்கு தரவுத்தளத்தில் அறுவடை பருவம் இல்லை. Grain Database இல் சேர்க்கவும்.',
    'procurement.month': 'மாதம் (விருப்பம்)',
    'procurement.selectHarvestSeasonFirst': 'முதலில் அறுவடை பருவத்தைத் தேர்ந்தெடுக்கவும்',
    'procurement.loadingMonths': 'மாதங்கள் ஏற்றப்படுகின்றன...',
    'procurement.noMonths': 'இந்த சேர்க்கைக்கு மாதம் இல்லை',
    'procurement.selectMonth': 'மாதத்தைத் தேர்ந்தெடுக்கவும் (விருப்பம்)',
    'procurement.addMonthsHint': 'இந்த சேர்க்கைக்கு தரவுத்தளத்தில் மாதம் இல்லை. Grain Database இல் சேர்க்கவும்.',
    'procurement.noOfSamples': 'மாதிரிகளின் எண்ணிக்கை (1–3)',
    'procurement.samplesPlaceholder': '1–3',
    'procurement.samplingMethod': 'மாதிரி முறை',
    'procurement.selectSamplingMethod': 'மாதிரி முறையைத் தேர்ந்தெடுக்கவும்',
    'procurement.handMilled': 'கை மில்',
    'procurement.machineMilled': 'மெஷின் மில்',
    'procurement.sampleSize': 'மாதிரி அளவு',
    'procurement.byWeight': 'எடையின்படி',
    'procurement.byCount': 'எண்ணிக்கையின்படி',
    'procurement.freeWeight': 'சுதந்திர எடை',
    'procurement.freeCount': 'சுதந்திர எண்ணிக்கை',
    'procurement.maxPlaceholder': 'அதிகபட்சம் {max}',
    'procurement.gramsUnit': 'கிராம்',
    'procurement.grainsUnit': 'தானியங்கள்',
    'procurement.parametersToAnalyse': 'பகுப்பாய்வு செய்ய வேண்டிய அளவுருக்கள்',
    'procurement.chalky': 'Chalky',
    'procurement.discolored': 'Discolored',
    'procurement.chalkyThreshold': 'Chalky த்ரெஷோல்டு',
    'procurement.purchasedData': 'கொள்முதல் தரவு',
    'procurement.mandi': 'மண்டி',
    'procurement.mandiPlaceholder': 'மண்டி / சந்தை',
    'procurement.vehicleNumber': 'வாகன எண்',
    'procurement.commaSeparatedPlaceholder': 'கமாவால் பிரிக்கவும்',
    'procurement.paddyPricePerKg': 'ஒரு கிலோ நெல் விலை (₹)',
    'procurement.kgPerBag': 'கிலோ / மூட்டை',
    'procurement.kgPerBagPlaceholder': 'ஒரு மூட்டைக்கு கிலோ',
    'procurement.noOfBags': 'மூட்டைகளின் எண்ணிக்கை',
    'procurement.transportationCost': 'போக்குவரத்து செலவு (₹)',
    'procurement.loadingCost': 'ஏற்றும் செலவு (₹)',
    'procurement.moistureSentByTrader': 'வியாபாரி அனுப்பிய நெல்லின் ஈரப்பதம் (%)',
    'procurement.yieldEstimation': 'விளைச்சல் மதிப்பீடு',
    'procurement.yieldEstimationInputs': 'விளைச்சல் மதிப்பீடு உள்ளீடுகள்',
    'procurement.actualInputMoisture': 'உண்மையான உள்ளீடு ஈரப்பதம் (%)',
    'procurement.impurities': 'கலப்படங்கள் (%)',
    'procurement.immatureGrains': 'முதிராத தானியங்கள் (%)',
    'procurement.husk': 'உமி (%)',
    'procurement.bran': 'தவிடு (%)',
    'procurement.headRicePct': 'Head Rice (%)',
    'procurement.autoCalculated': 'தானாக கணக்கிடப்படும்',
    'procurement.combinedBrokens': 'மொத்த உடைந்த அரிசி (%)',
    'procurement.calculatedAfterAnalysis': 'பகுப்பாய்வுக்குப் பிறகு கணக்கிடப்படும்',
    'procurement.marginMarketFee': 'மார்ஜின் / சந்தை கட்டணம் (₹)',
    'procurement.continueToLiveAnalysis': 'Live Analysis-க்குத் தொடரவும்',

    // Live Analysis — dynamic spoken guidance (machine series transitions)
    'liveGuide.machineDoneAnnouncement': '{machine} முடிந்தது. தயவுசெய்து {next}-க்கான அடுத்த மாதிரியை தயார் செய்யவும், தயாரானதும் Continue அழுத்தவும்.',
    'liveGuide.seriesCompleteAnnouncement': 'இந்த சீரிஸில் உள்ள அனைத்து மெஷின்களும் முடிந்தன. உங்கள் முடிவுகளைக் காண View Insights and Reports-ஐ அழுத்தவும்.',
    'liveGuide.sampleRunningAnnouncement': '{machine}-க்கு மாதிரி {n} இயங்குகிறது.',
  },
  te: {
    // Sidebar
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.massBalance': 'మాస్ బ్యాలెన్స్',
    'nav.knowYourGrains': 'మీ గింజలను తెలుసుకోండి',
    'nav.analytics': 'అనలిటిక్స్',
    'nav.dataReports': 'డేటా రిపోర్టులు',
    'nav.grainsViewer': 'గ్రెయిన్ వ్యూయర్',
    'nav.settings': 'సెట్టింగ్‌లు',
    'nav.manuals': 'మాన్యువల్స్',
    'nav.database': 'డేటాబేస్',
    'nav.grainDatabase': 'గ్రెయిన్ డేటాబేస్',
    'nav.machineDatabase': 'మెషిన్ డేటాబేస్',
    'nav.procurementAnalysis': 'కొనుగోలు విశ్లేషణ',
    'nav.productionAnalysis': 'ఉత్పత్తి విశ్లేషణ',
    'nav.milledRiceAnalysis': 'మిల్డ్ రైస్ క్వాలిటీ',
    'nav.navigation': 'నావిగేషన్',

    // Mass Balance page
    'massBalance.title': 'మాస్ బ్యాలెన్స్',
    'massBalance.subtitle': 'మొత్తం నమూనా బరువు నుండి భాగాల విభజనను లెక్కించండి',
    'massBalance.machineSelection': 'మెషిన్ ఎంపిక',
    'massBalance.machineA': 'మెషిన్ A',
    'massBalance.machineB': 'మెషిన్ B',
    'massBalance.selected': 'ఎంపిక చేయబడింది',
    'massBalance.machineADesc1': '• అధిక-ఖచ్చితత్వ రైస్ అనలైజర్',
    'massBalance.machineADesc2': '• ప్రాసెసింగ్ సామర్థ్యం: 100-500 గ్రా',
    'massBalance.machineADesc3': '• విశ్లేషణ సమయం: 2-3 నిమిషాలు',
    'massBalance.machineADesc4': '• ఖచ్చితత్వం: ±0.1%',
    'massBalance.machineBDesc1': '• అధునాతన మల్టీ-గ్రెయిన్ అనలైజర్',
    'massBalance.machineBDesc2': '• ప్రాసెసింగ్ సామర్థ్యం: 200-1000 గ్రా',
    'massBalance.machineBDesc3': '• విశ్లేషణ సమయం: 1-2 నిమిషాలు',
    'massBalance.machineBDesc4': '• ఖచ్చితత్వం: ±0.05%',
    'massBalance.precisionAnalyzer': 'ప్రెసిషన్ అనలైజర్',
    'massBalance.advancedMultiAnalyzer': 'అడ్వాన్స్‌డ్ మల్టీ-అనలైజర్',
    'massBalance.totalWeightInput': 'మొత్తం నమూనా బరువు ఇన్‌పుట్',
    'massBalance.enterTotalWeight': 'మొత్తం బరువును నమోదు చేయండి',
    'massBalance.usingMachine': 'ఉపయోగిస్తున్న మెషిన్',
    'massBalance.forAnalysis': 'విశ్లేషణ కోసం',
    'massBalance.breakdownFormula': 'విభజన ఫార్ములా',
    'massBalance.brownRice': 'బ్రౌన్ రైస్',
    'massBalance.husk': 'ఊక',
    'massBalance.bran': 'తవుడు',
    'massBalance.paddy': 'వడ్లు',
    'massBalance.calculatedBreakdown': 'లెక్కించిన విభజన',
    'massBalance.proceedToGrain': 'గ్రెయిన్ సమాచారానికి కొనసాగండి',

    // Know Your Grains page
    'knowGrains.title': 'మీ గింజలను తెలుసుకోండి',
    'knowGrains.subtitle': 'వివరణాత్మక గ్రెయిన్ లక్షణాలు మరియు పారామితులు',
    'knowGrains.previous': 'మునుపటి',
    'knowGrains.next': 'తదుపరి',
    'knowGrains.pageOf': 'పేజీ 1 / 1',
    'knowGrains.grainVisualization': 'గ్రెయిన్ విజువలైజేషన్',
    'knowGrains.visualDescription': 'రైస్ గ్రెయిన్ నమూనా విజువలైజేషన్',
    'knowGrains.visualSubtext': 'నమోదు చేసిన డేటా ఆధారంగా విజువల్ ప్రాతినిధ్యం అప్‌డేట్ అవుతుంది',
    'knowGrains.geoProperties': 'స్వరూప లక్షణాలు',
    'knowGrains.chemicalProperties': 'పోషక లక్షణాలు',
    'knowGrains.gmadProperties': 'GMAD లక్షణాలు',
    'knowGrains.length': 'పొడవు (మిమీ)',
    'knowGrains.breadth': 'వెడల్పు (మిమీ)',
    'knowGrains.weight': 'బరువు (మి.గ్రా)',
    'knowGrains.aspectRatio': 'ఆస్పెక్ట్ రేషియో',
    'knowGrains.hardness': 'కాఠిన్యం (HV)',
    'knowGrains.protein': 'ప్రోటీన్ (%)',
    'knowGrains.carbohydrate': 'కార్బోహైడ్రేట్ (%)',
    'knowGrains.vitamin': 'విటమిన్ (మి.గ్రా/100గ్రా)',
    'knowGrains.mineral': 'ఖనిజం (%)',
    'knowGrains.lipids': 'లిపిడ్స్ (%)',
    'knowGrains.gelatinization': 'జెలటినైజేషన్ ఉష్ణోగ్రత (°C)',
    'knowGrains.moisture': 'తేమ (%)',
    'knowGrains.age': 'వయస్సు (నెలలు)',
    'knowGrains.density': 'సాంద్రత (గ్రా/సెమీ³)',
    'knowGrains.addMoreInfo': 'మరింత సమాచారం జోడించండి',
    'knowGrains.continueToLive': 'లైవ్ అనాలిసిస్‌కు కొనసాగండి',
    'knowGrains.addProperty': 'కొత్త లక్షణాన్ని జోడించండి',
    'knowGrains.propertyName': 'లక్షణం పేరు',
    'knowGrains.propertyValue': 'లక్షణం విలువ',
    'knowGrains.propertyUnit': 'యూనిట్ (ఐచ్ఛికం)',
    'knowGrains.cancel': 'రద్దు చేయండి',
    'knowGrains.add': 'జోడించండి',

    // Settings
    'settings.language': 'భాష',
    'settings.hardware': 'హార్డ్‌వేర్',
    'settings.image': 'ఇమేజ్',
    'settings.reports': 'రిపోర్టులు',

    // Procurement Analysis — Test Preparation
    'procurement.tabPreparation': 'టెస్ట్ ప్రిపరేషన్',
    'procurement.tabLive': 'లైవ్ అనాలిసిస్',
    'procurement.tabReports': 'ఇన్‌సైట్స్ & రిపోర్టులు',
    'procurement.categoryPrefix': 'కేటగిరీ: {category}',
    'procurement.grainInformation': 'గ్రెయిన్ సమాచారం',
    'procurement.region': 'రీజియన్',
    'procurement.nonBasmati': 'నాన్-బాస్మతి',
    'procurement.basmati': 'బాస్మతి',
    'procurement.appliesSettingsNote': 'ఇది Settings పేజీలో కాన్ఫిగర్ చేసిన {category} సెట్టింగ్‌లను ఈ విశ్లేషణకు వర్తింపజేస్తుంది.',
    'procurement.variety': 'వెరైటీ',
    'procurement.loadingVarieties': 'వెరైటీలు లోడ్ అవుతున్నాయి...',
    'procurement.noVarietiesInDb': 'డేటాబేస్‌లో వెరైటీలు లేవు',
    'procurement.selectVariety': 'వెరైటీని ఎంచుకోండి',
    'procurement.addVarietiesHint': 'ముందుగా Grain Database లో వెరైటీలను జోడించండి; ఇక్కడ డేటాబేస్ వెరైటీలు మాత్రమే కనిపిస్తాయి.',
    'procurement.process': 'ప్రాసెస్',
    'procurement.selectVarietyFirst': 'ముందుగా వెరైటీని ఎంచుకోండి',
    'procurement.loadingProcesses': 'ప్రాసెస్‌లు లోడ్ అవుతున్నాయి...',
    'procurement.noProcessesForVariety': 'ఈ వెరైటీకి ప్రాసెస్‌లు లేవు',
    'procurement.selectProcess': 'ప్రాసెస్‌ను ఎంచుకోండి',
    'procurement.addProcessesHint': 'ఈ వెరైటీకి డేటాబేస్‌లో ప్రాసెస్ లేదు. Grain Database లో జోడించండి.',
    'procurement.harvestSeason': 'హార్వెస్ట్ సీజన్',
    'procurement.selectVarietyProcessFirst': 'ముందుగా వెరైటీ మరియు ప్రాసెస్‌ను ఎంచుకోండి',
    'procurement.loadingHarvestSeasons': 'హార్వెస్ట్ సీజన్‌లు లోడ్ అవుతున్నాయి...',
    'procurement.noHarvestSeasons': 'ఈ కలయికకు హార్వెస్ట్ సీజన్ లేదు',
    'procurement.selectHarvestSeason': 'హార్వెస్ట్ సీజన్‌ను ఎంచుకోండి',
    'procurement.addHarvestSeasonsHint': 'ఈ వెరైటీ + ప్రాసెస్‌కు డేటాబేస్‌లో హార్వెస్ట్ సీజన్ లేదు. Grain Database లో జోడించండి.',
    'procurement.month': 'నెల (ఐచ్ఛికం)',
    'procurement.selectHarvestSeasonFirst': 'ముందుగా హార్వెస్ట్ సీజన్‌ను ఎంచుకోండి',
    'procurement.loadingMonths': 'నెలలు లోడ్ అవుతున్నాయి...',
    'procurement.noMonths': 'ఈ కలయికకు నెలలు లేవు',
    'procurement.selectMonth': 'నెలను ఎంచుకోండి (ఐచ్ఛికం)',
    'procurement.addMonthsHint': 'ఈ కలయికకు డేటాబేస్‌లో నెలలు లేవు. Grain Database లో జోడించండి.',
    'procurement.noOfSamples': 'నమూనాల సంఖ్య (1–3)',
    'procurement.samplesPlaceholder': '1–3',
    'procurement.samplingMethod': 'నమూనా పద్ధతి',
    'procurement.selectSamplingMethod': 'నమూనా పద్ధతిని ఎంచుకోండి',
    'procurement.handMilled': 'హ్యాండ్ మిల్డ్',
    'procurement.machineMilled': 'మెషిన్ మిల్డ్',
    'procurement.sampleSize': 'నమూనా పరిమాణం',
    'procurement.byWeight': 'బరువు ప్రకారం',
    'procurement.byCount': 'లెక్క ప్రకారం',
    'procurement.freeWeight': 'ఫ్రీ బరువు',
    'procurement.freeCount': 'ఫ్రీ లెక్క',
    'procurement.maxPlaceholder': 'గరిష్టం {max}',
    'procurement.gramsUnit': 'గ్రాములు',
    'procurement.grainsUnit': 'గింజలు',
    'procurement.parametersToAnalyse': 'విశ్లేషించాల్సిన పారామితులు',
    'procurement.chalky': 'Chalky',
    'procurement.discolored': 'Discolored',
    'procurement.chalkyThreshold': 'Chalky థ్రెషోల్డ్',
    'procurement.purchasedData': 'కొనుగోలు డేటా',
    'procurement.mandi': 'మండి',
    'procurement.mandiPlaceholder': 'మండి / మార్కెట్',
    'procurement.vehicleNumber': 'వాహన నంబర్',
    'procurement.commaSeparatedPlaceholder': 'కామాతో వేరు చేయండి',
    'procurement.paddyPricePerKg': 'కిలోకు వడ్ల ధర (₹)',
    'procurement.kgPerBag': 'కిలో / బస్తా',
    'procurement.kgPerBagPlaceholder': 'బస్తాకు కిలోలు',
    'procurement.noOfBags': 'బస్తాల సంఖ్య',
    'procurement.transportationCost': 'రవాణా ఖర్చు (₹)',
    'procurement.loadingCost': 'లోడింగ్ ఖర్చు (₹)',
    'procurement.moistureSentByTrader': 'వ్యాపారి పంపిన వడ్ల తేమ (%)',
    'procurement.yieldEstimation': 'దిగుబడి అంచనా',
    'procurement.yieldEstimationInputs': 'దిగుబడి అంచనా ఇన్‌పుట్‌లు',
    'procurement.actualInputMoisture': 'వాస్తవ ఇన్‌పుట్ తేమ (%)',
    'procurement.impurities': 'మలినాలు (%)',
    'procurement.immatureGrains': 'అపరిపక్వ గింజలు (%)',
    'procurement.husk': 'ఊక (%)',
    'procurement.bran': 'తవుడు (%)',
    'procurement.headRicePct': 'Head Rice (%)',
    'procurement.autoCalculated': 'ఆటో-లెక్కింపు',
    'procurement.combinedBrokens': 'మొత్తం విరిగిన బియ్యం (%)',
    'procurement.calculatedAfterAnalysis': 'విశ్లేషణ తర్వాత లెక్కించబడుతుంది',
    'procurement.marginMarketFee': 'మార్జిన్ / మార్కెట్ ఫీజు (₹)',
    'procurement.continueToLiveAnalysis': 'Live Analysis‌కు కొనసాగండి',

    // Live Analysis — dynamic spoken guidance (machine series transitions)
    'liveGuide.machineDoneAnnouncement': '{machine} పూర్తయింది. దయచేసి {next} కోసం తదుపరి నమూనాను సిద్ధం చేయండి, సిద్ధమైనప్పుడు Continue నొక్కండి.',
    'liveGuide.seriesCompleteAnnouncement': 'ఈ సిరీస్‌లోని అన్ని మెషిన్‌లు పూర్తయ్యాయి. మీ ఫలితాలను చూడటానికి View Insights and Reports నొక్కండి.',
    'liveGuide.sampleRunningAnnouncement': '{machine} కోసం నమూనా {n} నడుస్తోంది.',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem(UI_LANGUAGE_STORAGE_KEY) as Language | null;
    return stored && AVAILABLE_LANGUAGES.some((l) => l.code === stored) ? stored : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(UI_LANGUAGE_STORAGE_KEY, lang);
  };

  // Stable reference (only changes when `language` does) so components can safely
  // depend on `t` inside useEffect without it re-firing on unrelated re-renders.
  const t = useCallback((key: string, vars?: Record<string, string | number>): string => {
    const raw = translations[language][key as keyof typeof translations['en']] || key;
    if (!vars) return raw;
    return raw.replace(/\{(\w+)\}/g, (_, k) => (vars[k] !== undefined ? String(vars[k]) : `{${k}}`));
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 